changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: Features
      labels:
        - enhancement
        - feature
    - title: Fixes
      labels:
        - bug
        - fix
    - title: Security
      labels:
        - security
    - title: Documentation & Maintenance
      labels:
        - documentation
        - maintenance
    - title: Other Changes
      labels:
        - "*"
